### ISSUE TITLE
Package this up

### ISSUE THREAD

**Issue by maelle** [rweekly/rweekly.highlights#3]
I'll make this a package called `rweekly.highlights` with a single `run_app()` function, to simplify use. :-)

**Comment by maelle** [comment]
@haozhu233 what a fast thumbs up! :open_mouth: I won't make the package as fast but I'll do my best to make this happen very soon. :pray:

**Comment by haozhu233** [comment]
@maelle haha I was holding my phone and saw the github email. What a great idea!
